# Generated by Django 3.2.10 on 2022-12-15 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Skill Name')),
                ('slug', models.SlugField(editable=False, max_length=100, primary_key=True, serialize=False, verbose_name='Skill Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, max_length=100, primary_key=True, serialize=False, verbose_name='Slug')),
                ('name', models.CharField(max_length=255, verbose_name='School Name')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('is_enabled', models.BooleanField(default=True, editable=False, verbose_name='Is Enabled')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', related_query_name='school', to='cities_light.city')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
