# Generated by Django 3.1.13 on 2021-12-14 18:35

from django.db import migrations, models
import django.db.models.deletion
import employer.constants


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
        ('candidate', '0002_auto_20211214_1835'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Employer Name')),
                ('industry', models.CharField(max_length=100, verbose_name='Industry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='External URL')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='Job Description')),
                ('min_yoe_required', models.IntegerField(verbose_name='Min YOE required')),
                ('max_salary', models.BigIntegerField(verbose_name='Max Salary in USD')),
                ('location', models.CharField(max_length=255, verbose_name='Job Location')),
                ('remote', models.CharField(choices=[('FULLY_REMOTE', employer.constants.Remote['FULLY_REMOTE']), ('HYBRID', employer.constants.Remote['HYBRID']), ('NO_REMOTE', employer.constants.Remote['NO_REMOTE'])], max_length=100, verbose_name='Remote?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', related_query_name='job', to='employer.employer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(max_length=100, verbose_name='Employee ID')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', related_query_name='employee', to='employer.employer')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BaseModel',
        ),
        migrations.AddField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', related_query_name='job', to='employer.recruiter'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.ManyToManyField(to='candidate.Skill'),
        ),
    ]
