# Generated by Django 3.1.13 on 2021-12-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_auto_20211214_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='remote',
            field=models.CharField(choices=[('FULLY_REMOTE', 'Fully Remote'), ('HYBRID', 'Hybrid'), ('NO_REMOTE', 'No Remote')], max_length=100, verbose_name='Remote?'),
        ),
    ]
