# Generated by Django 3.1.13 on 2021-12-14 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import job_board.users.constants


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Avatar')),
                ('role', models.CharField(choices=[('CANDIDATE', job_board.users.constants.Role['CANDIDATE']), ('EMPLOYER', job_board.users.constants.Role['EMPLOYER'])], max_length=50, verbose_name='Role')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('dob', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', related_query_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
            },
        ),
    ]
