# Generated by Django 3.1.13 on 2021-12-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('CANDIDATE', 'candidate'), ('EMPLOYER', 'employer')], max_length=50, verbose_name='Role'),
        ),
    ]
