# Generated by Django 3.2.10 on 2022-12-15 17:58

import candidate.constants
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('job', '__first__'),
        ('common', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('resume', models.FileField(upload_to='candidates/resumes')),
                ('onboarding_done', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
                ('saved_jobs', models.ManyToManyField(related_name='saved_by_candidates', related_query_name='saved_by_candidates', to='job.Job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateMisc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Candidate Achievements')),
                ('awards', models.TextField(blank=True, null=True, verbose_name='Candidate Awards')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('proficiency', models.IntegerField(choices=[(candidate.constants.Proficiency['ONE'], candidate.constants.Proficiency['ONE']), (candidate.constants.Proficiency['TWO'], candidate.constants.Proficiency['TWO']), (candidate.constants.Proficiency['THREE'], candidate.constants.Proficiency['THREE']), (candidate.constants.Proficiency['FOUR'], candidate.constants.Proficiency['FOUR']), (candidate.constants.Proficiency['FIVE'], candidate.constants.Proficiency['FIVE']), (candidate.constants.Proficiency['SIX'], candidate.constants.Proficiency['SIX']), (candidate.constants.Proficiency['SEVEN'], candidate.constants.Proficiency['SEVEN']), (candidate.constants.Proficiency['EIGHT'], candidate.constants.Proficiency['EIGHT']), (candidate.constants.Proficiency['NINE'], candidate.constants.Proficiency['NINE']), (candidate.constants.Proficiency['TEN'], candidate.constants.Proficiency['TEN'])], verbose_name='Proficiency')),
                ('yoe', models.IntegerField(verbose_name='Years of Experience')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skills', related_query_name='candidate_skill', to='candidate.candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skills', related_query_name='candidate_skill', to='common.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_projects', related_query_name='candidate_project', to='candidate.candidate')),
                ('skills_used', models.ManyToManyField(to='common.Skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidatePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('expected_salary', models.IntegerField(verbose_name='Expected Salary')),
                ('current_salary', models.IntegerField(verbose_name='Expected Salary')),
                ('job_search_status', models.CharField(choices=[(candidate.constants.JobSearchChoices['ACTIVELY_LOOKING'], 'Actively Looking'), (candidate.constants.JobSearchChoices['PASSIVELY_LOOKING'], 'Passively Looking'), (candidate.constants.JobSearchChoices['NOT_LOOKING'], 'Not Looking At The Moment')], max_length=100, verbose_name='Job Search Status')),
                ('profile_privacy', models.CharField(choices=[(candidate.constants.ProfilePrivacyChoices['NONE'], 'No one! Hide from everyone'), (candidate.constants.ProfilePrivacyChoices['ALL'], 'Everyone!'), (candidate.constants.ProfilePrivacyChoices['ONLY_TO_WHOSE_JOBS_I_APPLIED_TO'], 'Recruiters to whose jobs I applied!')], max_length=100, verbose_name='Who can see your profile?')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_prefs', related_query_name='candidate_pref', to='candidate.candidate')),
                ('current_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_candidates', related_query_name='preferred_candidate', to='cities_light.city')),
                ('desired_cities', models.ManyToManyField(related_name='desired_candidates', related_query_name='desired_candidates', to='cities_light.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('company', models.CharField(max_length=255, verbose_name='Company Name')),
                ('role', models.CharField(max_length=255, verbose_name='Role')),
                ('responsibilities', models.TextField(verbose_name='Responsibilities')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_experiences', related_query_name='candidate_experience', to='candidate.candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('degree', models.CharField(max_length=100, verbose_name='Degree')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_educations', related_query_name='candidate_education', to='candidate.candidate')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_educations', related_query_name='candidate_education', to='common.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Alert Name')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('filters', models.TextField(verbose_name='Filters')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', related_query_name='alert', to='candidate.candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
