# Generated by Django 3.2.10 on 2022-09-30 06:19

import candidate.constants
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('resume', models.FileField(upload_to='candidates/resumes')),
                ('onboarding_done', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateMisc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Candidate Achievements')),
                ('awards', models.TextField(blank=True, null=True, verbose_name='Candidate Awards')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='School Name')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField(max_length=25, primary_key=True, serialize=False, verbose_name='Skill Name')),
                ('proficiency', models.IntegerField(choices=[(1, candidate.constants.Proficiency['ONE']), (2, candidate.constants.Proficiency['TWO']), (3, candidate.constants.Proficiency['THREE']), (4, candidate.constants.Proficiency['FOUR']), (5, candidate.constants.Proficiency['FIVE']), (6, candidate.constants.Proficiency['SIX']), (7, candidate.constants.Proficiency['SEVEN']), (8, candidate.constants.Proficiency['EIGHT']), (9, candidate.constants.Proficiency['NINE']), (10, candidate.constants.Proficiency['TEN'])], null=True, verbose_name='Proficiency')),
                ('yoe', models.IntegerField(null=True, verbose_name='Years of Experience')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skills', related_query_name='candidate_skill', to='candidate.candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skills', related_query_name='candidate_skill', to='candidate.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_projects', related_query_name='candidate_project', to='candidate.candidate')),
                ('skills_used', models.ManyToManyField(to='candidate.Skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('company', models.CharField(max_length=255, verbose_name='Company Name')),
                ('role', models.CharField(max_length=255, verbose_name='Role')),
                ('responsibilities', models.TextField(verbose_name='Responsibilities')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_experiences', related_query_name='candidate_experience', to='candidate.candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('degree', models.CharField(max_length=100, verbose_name='Degree')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_educations', related_query_name='candidate_education', to='candidate.candidate')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_educations', related_query_name='candidate_education', to='candidate.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
