# Generated by Django 3.2.10 on 2023-01-06 08:25

import candidate.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepreference',
            name='total_yoe',
            field=models.IntegerField(blank=True, help_text='Enter zero if you are a fresher.', null=True, verbose_name='Total Years of Experience?'),
        ),
        migrations.AlterField(
            model_name='candidatepreference',
            name='current_salary',
            field=models.IntegerField(help_text="We won't tell this to anyone.", verbose_name='Expected Salary'),
        ),
        migrations.AlterField(
            model_name='candidatepreference',
            name='profile_privacy',
            field=models.CharField(choices=[(candidate.constants.ProfilePrivacyChoices['NONE'], 'No one! Hide from everyone'), (candidate.constants.ProfilePrivacyChoices['ALL'], 'Everyone!'), (candidate.constants.ProfilePrivacyChoices['ONLY_TO_WHOSE_JOBS_I_APPLIED_TO'], 'Recruiters to whose jobs I applied!')], help_text='Be diligent in setting this', max_length=100, verbose_name='Who can see your profile?'),
        ),
    ]
