# Generated by Django 3.2.10 on 2023-01-06 09:06

import candidate.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_auto_20230106_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepreference',
            name='job_search_status',
            field=models.CharField(choices=[('ACTIVELY_LOOKING', 'Actively Looking'), ('PASSIVELY_LOOKING', 'Passively Looking'), ('NOT_LOOKING', 'Not Looking At The Moment')], max_length=100, verbose_name='Job Search Status'),
        ),
        migrations.AlterField(
            model_name='candidatepreference',
            name='profile_privacy',
            field=models.CharField(choices=[('NONE', 'No one! Hide from everyone'), (candidate.constants.ProfilePrivacyChoices['ALL'], 'Everyone!'), ('ONLY_TO_WHOSE_JOBS_I_APPLIED_TO', 'Recruiters to whose jobs I applied!')], help_text='Be diligent in setting this', max_length=100, verbose_name='Who can see your profile?'),
        ),
        migrations.AlterField(
            model_name='candidateskill',
            name='proficiency',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Proficiency'),
        ),
    ]
