# Generated by Django 3.2.10 on 2023-01-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20230106_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepreference',
            name='profile_privacy',
            field=models.CharField(choices=[('NONE', 'No one! Hide from everyone'), ('ALL', 'Everyone!'), ('ONLY_TO_WHOSE_JOBS_I_APPLIED_TO', 'Recruiters to whose jobs I applied!')], help_text='Be diligent in setting this', max_length=100, verbose_name='Who can see your profile?'),
        ),
    ]
