# Generated by Django 3.2.10 on 2022-12-15 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=125, verbose_name='Company Name')),
                ('slug', models.SlugField(editable=False, max_length=125, primary_key=True, serialize=False, verbose_name='Company Slug')),
                ('industry', models.CharField(help_text='Which industry does it belong to? Examples: Software Engineering, Manufacturing', max_length=100, verbose_name='Industry')),
                ('size', models.CharField(help_text="What's the employee headcount?", max_length=100, verbose_name='Company Size')),
                ('about', models.TextField(help_text='Write about the company. It will be displayed on the web page to the users.', verbose_name='About Company')),
                ('logo', models.ImageField(help_text='Logo of the company', upload_to='recruiters/company/logo', verbose_name='Logo of the company')),
                ('url', models.URLField(help_text='URL of the company website', verbose_name='Website URL')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', related_query_name='company', to='cities_light.city')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('companies', models.ManyToManyField(to='recruiter.Company')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
