# Generated by Django 3.2.10 on 2022-10-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiter", "0002_auto_20221008_1607"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "companies"},
        )
    ]
