# Generated by Django 3.2.10 on 2022-12-15 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiter', '__first__'),
        ('common', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Category Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='External URL')),
                ('job_description', models.TextField(verbose_name='Job Description')),
                ('job_title', models.CharField(help_text='This will be displayed as the title of the web page.', max_length=100, verbose_name='Job Title')),
                ('position', models.CharField(help_text='Example : Account Executive, Software Engineer', max_length=100, verbose_name='Position')),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract')], max_length=100, verbose_name='Job Type')),
                ('min_yoe_required', models.IntegerField(verbose_name='Minimum years of experience required')),
                ('min_salary', models.BigIntegerField(verbose_name='Min Salary in USD')),
                ('max_salary', models.BigIntegerField(verbose_name='Max Salary in USD')),
                ('location', models.CharField(max_length=255, verbose_name='Job Location')),
                ('remote', models.CharField(choices=[('FULLY_REMOTE', 'Fully Remote'), ('HYBRID', 'Hybrid'), ('NO_REMOTE', 'No Remote')], max_length=100, verbose_name='Remote?')),
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Slug')),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('EXPIRED', 'expired')], default='ACTIVE', max_length=25, verbose_name='Status')),
                ('active_till', models.DateTimeField(verbose_name='Active Till')),
                ('categories', models.ManyToManyField(related_name='jobs', related_query_name='jobs', to='job.Category')),
                ('company', models.ForeignKey(help_text='The details of the company such as about, size, industry etc... will be populated on the job page. If no company is shown, create a new company from the dashboard', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', related_query_name='job', to='recruiter.company')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', related_query_name='job', to='recruiter.recruiter')),
                ('skills_required', models.ManyToManyField(related_name='jobs', related_query_name='jobs', to='common.Skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(choices=[('ACTIVE', 'active'), ('EXPIRED', 'expired')], max_length=25)),
                ('new_status', models.CharField(choices=[('ACTIVE', 'active'), ('EXPIRED', 'expired')], max_length=25)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
