# Generated by Django 3.2.10 on 2022-09-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='External URL')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='Job Description')),
                ('job_title', models.CharField(help_text='This will be displayed on the web page.', max_length=100, verbose_name='Job Title')),
                ('position', models.CharField(help_text='Example : Account Executive, Software Engineer', max_length=100, verbose_name='Position')),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract')], max_length=100, verbose_name='Job Type')),
                ('min_yoe_required', models.IntegerField(verbose_name='Minimum years of experience required')),
                ('min_salary', models.BigIntegerField(verbose_name='Min Salary in USD')),
                ('max_salary', models.BigIntegerField(verbose_name='Max Salary in USD')),
                ('location', models.CharField(max_length=255, verbose_name='Job Location')),
                ('remote', models.CharField(choices=[('FULLY_REMOTE', 'Fully Remote'), ('HYBRID', 'Hybrid'), ('NO_REMOTE', 'No Remote')], max_length=100, verbose_name='Remote?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', related_query_name='job', to='recruiter.company')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', related_query_name='job', to='recruiter.recruiter')),
                ('skills_required', models.ManyToManyField(to='candidate.Skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
