# Generated by Django 3.2.10 on 2022-10-08 16:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_auto_20221003_0744"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="active_till",
            field=models.DateTimeField(verbose_name="Active Till", null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="slug",
            field=models.SlugField(
                null=True,
                verbose_name="Slug",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "active"), ("EXPIRED", "expired")],
                default="ACTIVE",
                max_length=25,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="JobStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "old_status",
                    models.CharField(
                        choices=[("ACTIVE", "active"), ("EXPIRED", "expired")],
                        max_length=25,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[("ACTIVE", "active"), ("EXPIRED", "expired")],
                        max_length=25,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="job.job"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
