# Generated by Django 3.2.10 on 2023-01-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, primary_key=True, serialize=False, verbose_name='Slug'),
        ),
    ]
