# Generated by Django 3.2.10 on 2022-10-08 16:14
import random
from textwrap import fill
from django.db import migrations


def fill_values_for_slug_field(apps, _schema_editor):
    job = apps.get_model("job", "Job")
    for job in job.objects.all():
        job.slug = "%s-%s--%s" % (
            job.company.name,
            job.position,
            random.randint(0, 10000),
        )
        job.save()


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_auto_20221008_1605"),
    ]

    operations = [
        migrations.RunPython(fill_values_for_slug_field),
    ]
