# Generated by Django 3.2.10 on 2023-02-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='Score'),
        ),
    ]
