# Generated by Django 3.2.10 on 2022-10-09 02:08

from django.db import migrations, models
from django.utils import timezone
from django.conf import settings


def update_job_active_till(apps, _schem_editor):
    job = apps.get_model("job", "Job")
    for job in job.objects.all():
        job.active_till = timezone.now() + timezone.timedelta(
            days=settings.DEFAULT_JOB_ACTIVE_IN_DAYS
        )
        job.save()


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0005_alter_job_slug"),
    ]

    operations = [
        migrations.RunPython(update_job_active_till),
        migrations.AlterField(
            model_name="job",
            name="active_till",
            field=models.SlugField(verbose_name="Active Till", null=False),
        ),
    ]
