# Generated by Django 3.2.10 on 2022-10-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_update_job_active_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='active_till',
            field=models.DateTimeField(verbose_name='Active Till'),
        ),
    ]
